### ISSUE TITLE
请教微信的 feed 你是怎么处理的？

### ISSUE THREAD

**Issue by winguse** [henix/feeds#1]
单纯比较好奇：

1. 搜狗微信搜索，人肉打码？
2. root 设备上的微信 App？

冒昧打扰了。

**Comment by henix** [comment]
嗯，欢迎探讨。我是 1 ，验证码输入一次大概能维持几小时吧。

**Comment by winguse** [comment]
我有个想法，人肉打码：遇到验证码的时候，用微信的接口，将验证码发给自己。http://admin.wechat.com/debug/sandbox 这个可以发服务消息。然后自己恢复就好了，这样可以丢在服务器上跑。

**Comment by henix** [comment]
嗯，不错。尽可能控制抓取频率，可以尽量减少验证码。
