### ISSUE TITLE
rss 输出的时间有问题

### ISSUE THREAD

**Issue by wizos** [henix/feeds#2]
rss 输出项中的时间在 Inoreader 中会被识别为2016年12月

**Comment by henix** [comment]
请问是哪个 feed，只有一条还是所有的？

**Comment by wizos** [comment]
所有的都是这样。例如：
![image](https://user-images.githubusercontent.com/10218866/30169302-9db49892-941e-11e7-8382-e24e88c3bced.png)

![image](https://user-images.githubusercontent.com/10218866/30169734-d9d42bf2-941f-11e7-8b58-fc231c22ff98.png)

**Comment by henix** [comment]
谢了，找到原因了。

**Comment by wizos** [comment]
什么原因呢？我看item的pubDate似乎是正常的

**Comment by henix** [comment]
你可以看看我上面的两个提交
