### ISSUE TITLE
请问有 王垠 博客的源代码吗？

### ISSUE THREAD

**Issue by bequt** [henix/feeds#3]
请问有**王垠**博客的源代码吗？

**Comment by bequt** [comment]
看起来那么好的博客排版，我想仿照写一个。谢谢。

**Comment by henix** [comment]
我这里只抓了内容，你可以在 github 上搜一下 yinwang 。

**Comment by homeless2010** [comment]
> 请问有**王垠**博客的源代码吗？

找到了吗
